[phases.setup]
nixPkgs = ['nodejs_20', 'git-lfs']

[phases.install]
cmds = ['git lfs install', 'git lfs pull', 'npm ci']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm start'

[variables]
# GITHUB_TOKEN is only needed at runtime, not during build
GITHUB_TOKEN = ''
